// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
