// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type User struct {
	Name string `json:"name"`
}

type UserInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
